[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
dependsOn = []
cmds = [
    "chmod +x railway-build.sh",
    "./railway-build.sh"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "cd client && npm run build"
]

[start]
cmd = "npm start"

